# Site settings
title: Daniel
email: danvdboo@gmail.com
url: https://DanvdBoo.github.io
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
keywords: "your keywords, separated by commas"
skills: "Computer Science Student at TU Delft"
meta_author: Daniel van den Boogaard

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 4d16c1 #18bc9c #80B3FF
  primary-rgb: "77,22,193" #"24,288,156" #"128,179,255"
  secondary: 5572F0 #2c3e50 #FD6E8A
  secondary-dark: 264bec #233140 #A2122F

# Footer settings
footer:
  copyright: Daniel van den Boogaard
  location: Contact Details
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  # - title: stack-overflow
  # - title: bitbucket
  - title: github
    url: http://github.com/DanvdBoo
  - title: linkedin
    url: https://www.linkedin.com/in/daniel-van-den-boogaard-ba7248150

# Postal address (add as many lines as necessary)
address:
  - line: Daniel van den Boogaard
  - line: Voorburg, The Netherlands
  - line: +31 6 423 080 76
  - line: danvdboo@gmail.com

# Credits content
credits: 'Theme by <a href="http://startbootstrap.com">Start Bootstrap</a> Art by <a href="http://danvdboo.github.io">danvdboo</a>'

# Build settings
markdown: kramdown
permalink: pretty
